SET V_MINIGIGDBSERVER=LENOVITO-PC\SQLEXPRESS
SET V_WEBSITENAME=EMiniGig
SET V_WEBPORT=99
msiexec /i "WixInstaller.msi" WEB.SITENAME="%V_WEBSITENAME%" WEB.PORT="%V_WEBPORT%" ^
MINIGIG.DB.SERVER="%V_MINIGIGDBSERVER%" /l*vx install.log